name: 'check-deploy-action'
description: ''
author: 'SMENA'
inputs:
  youtrack_token:
    description: 'youtrack token'
  repo_token:
    description: 'token for commenting PRs'
  youtrack_url:
    description: 'base url of youtrack'
  base_url:
    description: 'base_url of remote site'
  basic_login:
    description: 'basic_login for remote site auth'
  basic_password:
    description: 'basic_password for remote site auth'

runs:
  using: 'node12'
  main: 'dist/index.js'
